// Top ~1000 popular stocks, ETFs, and indices for instant local search.
// Falls back to Yahoo Finance API for symbols not in this list.

export interface LocalSymbol {
  symbol: string;
  name: string;
  exchange: string;
}

export const POPULAR_STOCKS: LocalSymbol[] = [
  // === US Mega-Cap / S&P 500 Top Holdings ===
  { symbol: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', exchange: 'NASDAQ' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A', exchange: 'NASDAQ' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C', exchange: 'NASDAQ' },
  { symbol: 'META', name: 'Meta Platforms Inc.', exchange: 'NASDAQ' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Inc. Class B', exchange: 'NYSE' },
  { symbol: 'BRK-A', name: 'Berkshire Hathaway Inc. Class A', exchange: 'NYSE' },
  { symbol: 'TSLA', name: 'Tesla Inc.', exchange: 'NASDAQ' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.', exchange: 'NYSE' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', exchange: 'NYSE' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', exchange: 'NYSE' },
  { symbol: 'V', name: 'Visa Inc.', exchange: 'NYSE' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE' },
  { symbol: 'WMT', name: 'Walmart Inc.', exchange: 'NYSE' },
  { symbol: 'MA', name: 'Mastercard Incorporated', exchange: 'NYSE' },
  { symbol: 'PG', name: 'Procter & Gamble Company', exchange: 'NYSE' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ' },
  { symbol: 'HD', name: 'Home Depot Inc.', exchange: 'NYSE' },
  { symbol: 'CVX', name: 'Chevron Corporation', exchange: 'NYSE' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', exchange: 'NYSE' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', exchange: 'NASDAQ' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', exchange: 'NASDAQ' },
  { symbol: 'KO', name: 'Coca-Cola Company', exchange: 'NYSE' },
  { symbol: 'ADBE', name: 'Adobe Inc.', exchange: 'NASDAQ' },
  { symbol: 'CRM', name: 'Salesforce Inc.', exchange: 'NYSE' },
  { symbol: 'MCD', name: 'McDonald\'s Corporation', exchange: 'NYSE' },
  { symbol: 'BAC', name: 'Bank of America Corporation', exchange: 'NYSE' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', exchange: 'NASDAQ' },
  { symbol: 'NFLX', name: 'Netflix Inc.', exchange: 'NASDAQ' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', exchange: 'NASDAQ' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.', exchange: 'NYSE' },
  { symbol: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE' },
  { symbol: 'ORCL', name: 'Oracle Corporation', exchange: 'NYSE' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', exchange: 'NASDAQ' },
  { symbol: 'ACN', name: 'Accenture plc', exchange: 'NYSE' },
  { symbol: 'DHR', name: 'Danaher Corporation', exchange: 'NYSE' },
  { symbol: 'DIS', name: 'Walt Disney Company', exchange: 'NYSE' },
  { symbol: 'PM', name: 'Philip Morris International', exchange: 'NYSE' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.', exchange: 'NASDAQ' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.', exchange: 'NYSE' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.', exchange: 'NYSE' },
  { symbol: 'INTC', name: 'Intel Corporation', exchange: 'NASDAQ' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', exchange: 'NYSE' },
  { symbol: 'T', name: 'AT&T Inc.', exchange: 'NYSE' },
  { symbol: 'COP', name: 'ConocoPhillips', exchange: 'NYSE' },
  { symbol: 'INTU', name: 'Intuit Inc.', exchange: 'NASDAQ' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company', exchange: 'NYSE' },
  { symbol: 'UNP', name: 'Union Pacific Corporation', exchange: 'NYSE' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', exchange: 'NYSE' },
  { symbol: 'AMGN', name: 'Amgen Inc.', exchange: 'NASDAQ' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', exchange: 'NYSE' },
  { symbol: 'BA', name: 'Boeing Company', exchange: 'NYSE' },
  { symbol: 'IBM', name: 'International Business Machines', exchange: 'NYSE' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.', exchange: 'NASDAQ' },
  { symbol: 'GE', name: 'GE Aerospace', exchange: 'NYSE' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', exchange: 'NYSE' },
  { symbol: 'RTX', name: 'RTX Corporation', exchange: 'NYSE' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', exchange: 'NASDAQ' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.', exchange: 'NYSE' },
  { symbol: 'LOW', name: 'Lowe\'s Companies Inc.', exchange: 'NYSE' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation', exchange: 'NYSE' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', exchange: 'NASDAQ' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', exchange: 'NASDAQ' },
  { symbol: 'DE', name: 'Deere & Company', exchange: 'NYSE' },
  { symbol: 'SYK', name: 'Stryker Corporation', exchange: 'NYSE' },
  { symbol: 'BLK', name: 'BlackRock Inc.', exchange: 'NYSE' },
  { symbol: 'ADP', name: 'Automatic Data Processing', exchange: 'NASDAQ' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.', exchange: 'NASDAQ' },
  { symbol: 'PLD', name: 'Prologis Inc.', exchange: 'NYSE' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', exchange: 'NASDAQ' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', exchange: 'NASDAQ' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies', exchange: 'NYSE' },
  { symbol: 'AXP', name: 'American Express Company', exchange: 'NYSE' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.', exchange: 'NASDAQ' },
  { symbol: 'CB', name: 'Chubb Limited', exchange: 'NYSE' },
  { symbol: 'ETN', name: 'Eaton Corporation plc', exchange: 'NYSE' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', exchange: 'NASDAQ' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', exchange: 'NASDAQ' },
  { symbol: 'SCHW', name: 'Charles Schwab Corporation', exchange: 'NYSE' },
  { symbol: 'CI', name: 'Cigna Group', exchange: 'NYSE' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', exchange: 'NASDAQ' },
  { symbol: 'MO', name: 'Altria Group Inc.', exchange: 'NYSE' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', exchange: 'NYSE' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', exchange: 'NASDAQ' },
  { symbol: 'SO', name: 'Southern Company', exchange: 'NYSE' },
  { symbol: 'DUK', name: 'Duke Energy Corporation', exchange: 'NYSE' },
  { symbol: 'SLB', name: 'Schlumberger Limited', exchange: 'NYSE' },
  { symbol: 'KLAC', name: 'KLA Corporation', exchange: 'NASDAQ' },
  { symbol: 'BSX', name: 'Boston Scientific Corporation', exchange: 'NYSE' },
  { symbol: 'CME', name: 'CME Group Inc.', exchange: 'NASDAQ' },
  { symbol: 'FI', name: 'Fiserv Inc.', exchange: 'NYSE' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc.', exchange: 'NYSE' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', exchange: 'NYSE' },
  { symbol: 'EOG', name: 'EOG Resources Inc.', exchange: 'NYSE' },
  { symbol: 'MU', name: 'Micron Technology Inc.', exchange: 'NASDAQ' },
  { symbol: 'CL', name: 'Colgate-Palmolive Company', exchange: 'NYSE' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', exchange: 'NASDAQ' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', exchange: 'NASDAQ' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc.', exchange: 'NYSE' },
  { symbol: 'SHW', name: 'Sherwin-Williams Company', exchange: 'NYSE' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', exchange: 'NASDAQ' },
  { symbol: 'PNC', name: 'PNC Financial Services', exchange: 'NYSE' },
  { symbol: 'MCO', name: 'Moody\'s Corporation', exchange: 'NYSE' },
  { symbol: 'USB', name: 'U.S. Bancorp', exchange: 'NYSE' },
  { symbol: 'AON', name: 'Aon plc', exchange: 'NYSE' },
  { symbol: 'MSI', name: 'Motorola Solutions Inc.', exchange: 'NYSE' },
  { symbol: 'TJX', name: 'TJX Companies Inc.', exchange: 'NYSE' },
  { symbol: 'ATVI', name: 'Activision Blizzard Inc.', exchange: 'NASDAQ' },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation', exchange: 'NYSE' },
  { symbol: 'EMR', name: 'Emerson Electric Co.', exchange: 'NYSE' },
  { symbol: 'GD', name: 'General Dynamics Corporation', exchange: 'NYSE' },
  { symbol: 'APD', name: 'Air Products and Chemicals', exchange: 'NYSE' },
  { symbol: 'ORLY', name: 'O\'Reilly Automotive Inc.', exchange: 'NASDAQ' },
  { symbol: 'FDX', name: 'FedEx Corporation', exchange: 'NYSE' },
  { symbol: 'PSX', name: 'Phillips 66', exchange: 'NYSE' },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', exchange: 'NASDAQ' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.', exchange: 'NYSE' },
  { symbol: 'CTAS', name: 'Cintas Corporation', exchange: 'NASDAQ' },
  { symbol: 'AIG', name: 'American International Group', exchange: 'NYSE' },
  { symbol: 'CSX', name: 'CSX Corporation', exchange: 'NASDAQ' },
  { symbol: 'AZO', name: 'AutoZone Inc.', exchange: 'NYSE' },
  { symbol: 'ROP', name: 'Roper Technologies Inc.', exchange: 'NASDAQ' },
  { symbol: 'TGT', name: 'Target Corporation', exchange: 'NYSE' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill', exchange: 'NYSE' },
  { symbol: 'CARR', name: 'Carrier Global Corporation', exchange: 'NYSE' },
  { symbol: 'NSC', name: 'Norfolk Southern Corporation', exchange: 'NYSE' },
  { symbol: 'ECL', name: 'Ecolab Inc.', exchange: 'NYSE' },
  { symbol: 'GM', name: 'General Motors Company', exchange: 'NYSE' },
  { symbol: 'F', name: 'Ford Motor Company', exchange: 'NYSE' },
  { symbol: 'D', name: 'Dominion Energy Inc.', exchange: 'NYSE' },
  { symbol: 'MCK', name: 'McKesson Corporation', exchange: 'NYSE' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corp.', exchange: 'NYSE' },
  { symbol: 'DXCM', name: 'DexCom Inc.', exchange: 'NASDAQ' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.', exchange: 'NASDAQ' },
  { symbol: 'MNST', name: 'Monster Beverage Corporation', exchange: 'NASDAQ' },
  { symbol: 'PSA', name: 'Public Storage', exchange: 'NYSE' },
  { symbol: 'HUM', name: 'Humana Inc.', exchange: 'NYSE' },
  { symbol: 'AEP', name: 'American Electric Power', exchange: 'NASDAQ' },
  { symbol: 'MAR', name: 'Marriott International', exchange: 'NASDAQ' },
  { symbol: 'WELL', name: 'Welltower Inc.', exchange: 'NYSE' },
  { symbol: 'SRE', name: 'Sempra', exchange: 'NYSE' },
  { symbol: 'KMB', name: 'Kimberly-Clark Corporation', exchange: 'NYSE' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', exchange: 'NASDAQ' },
  { symbol: 'O', name: 'Realty Income Corporation', exchange: 'NYSE' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corp.', exchange: 'NYSE' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.', exchange: 'NYSE' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corp.', exchange: 'NYSE' },
  { symbol: 'AFL', name: 'Aflac Inc.', exchange: 'NYSE' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.', exchange: 'NASDAQ' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', exchange: 'NASDAQ' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.', exchange: 'NYSE' },
  { symbol: 'TFC', name: 'Truist Financial Corporation', exchange: 'NYSE' },
  { symbol: 'MSCI', name: 'MSCI Inc.', exchange: 'NYSE' },
  { symbol: 'VLO', name: 'Valero Energy Corporation', exchange: 'NYSE' },
  { symbol: 'EXC', name: 'Exelon Corporation', exchange: 'NASDAQ' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.', exchange: 'NASDAQ' },
  { symbol: 'GIS', name: 'General Mills Inc.', exchange: 'NYSE' },
  { symbol: 'HLT', name: 'Hilton Worldwide Holdings', exchange: 'NYSE' },
  { symbol: 'NEM', name: 'Newmont Corporation', exchange: 'NYSE' },
  { symbol: 'YUM', name: 'Yum! Brands Inc.', exchange: 'NYSE' },
  { symbol: 'STZ', name: 'Constellation Brands Inc.', exchange: 'NYSE' },
  { symbol: 'PAYX', name: 'Paychex Inc.', exchange: 'NASDAQ' },
  { symbol: 'KHC', name: 'Kraft Heinz Company', exchange: 'NASDAQ' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line', exchange: 'NASDAQ' },
  { symbol: 'ON', name: 'ON Semiconductor Corp.', exchange: 'NASDAQ' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.', exchange: 'NASDAQ' },
  { symbol: 'BK', name: 'Bank of New York Mellon', exchange: 'NYSE' },
  { symbol: 'GPN', name: 'Global Payments Inc.', exchange: 'NYSE' },
  { symbol: 'CCI', name: 'Crown Castle Inc.', exchange: 'NYSE' },
  { symbol: 'KR', name: 'Kroger Co.', exchange: 'NYSE' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises', exchange: 'NYSE' },
  { symbol: 'DHI', name: 'D.R. Horton Inc.', exchange: 'NYSE' },
  { symbol: 'LEN', name: 'Lennar Corporation', exchange: 'NYSE' },
  { symbol: 'CTVA', name: 'Corteva Inc.', exchange: 'NYSE' },
  { symbol: 'AME', name: 'AMETEK Inc.', exchange: 'NYSE' },
  { symbol: 'IQV', name: 'IQVIA Holdings Inc.', exchange: 'NYSE' },
  { symbol: 'FAST', name: 'Fastenal Company', exchange: 'NASDAQ' },
  { symbol: 'EA', name: 'Electronic Arts Inc.', exchange: 'NASDAQ' },
  { symbol: 'A', name: 'Agilent Technologies Inc.', exchange: 'NYSE' },
  { symbol: 'HSY', name: 'Hershey Company', exchange: 'NYSE' },
  { symbol: 'BIIB', name: 'Biogen Inc.', exchange: 'NASDAQ' },
  { symbol: 'GEHC', name: 'GE HealthCare Technologies', exchange: 'NASDAQ' },
  { symbol: 'IT', name: 'Gartner Inc.', exchange: 'NYSE' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions', exchange: 'NASDAQ' },
  { symbol: 'ROK', name: 'Rockwell Automation Inc.', exchange: 'NYSE' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.', exchange: 'NASDAQ' },
  { symbol: 'CPRT', name: 'Copart Inc.', exchange: 'NASDAQ' },
  { symbol: 'DOW', name: 'Dow Inc.', exchange: 'NYSE' },
  { symbol: 'DD', name: 'DuPont de Nemours Inc.', exchange: 'NYSE' },
  { symbol: 'HAL', name: 'Halliburton Company', exchange: 'NYSE' },
  { symbol: 'EL', name: 'Estée Lauder Companies', exchange: 'NYSE' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', exchange: 'NASDAQ' },
  { symbol: 'NKE', name: 'NIKE Inc.', exchange: 'NYSE' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', exchange: 'NASDAQ' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.', exchange: 'NYSE' },
  { symbol: 'DASH', name: 'DoorDash Inc.', exchange: 'NASDAQ' },
  { symbol: 'SNAP', name: 'Snap Inc.', exchange: 'NYSE' },
  { symbol: 'SQ', name: 'Block Inc.', exchange: 'NYSE' },
  { symbol: 'SHOP', name: 'Shopify Inc.', exchange: 'NYSE' },
  { symbol: 'COIN', name: 'Coinbase Global Inc.', exchange: 'NASDAQ' },
  { symbol: 'ROKU', name: 'Roku Inc.', exchange: 'NASDAQ' },
  { symbol: 'RBLX', name: 'Roblox Corporation', exchange: 'NYSE' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.', exchange: 'NYSE' },
  { symbol: 'SNOW', name: 'Snowflake Inc.', exchange: 'NYSE' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', exchange: 'NASDAQ' },
  { symbol: 'DDOG', name: 'Datadog Inc.', exchange: 'NASDAQ' },
  { symbol: 'ZS', name: 'Zscaler Inc.', exchange: 'NASDAQ' },
  { symbol: 'NET', name: 'Cloudflare Inc.', exchange: 'NYSE' },
  { symbol: 'PINS', name: 'Pinterest Inc.', exchange: 'NYSE' },
  { symbol: 'TTD', name: 'Trade Desk Inc.', exchange: 'NASDAQ' },
  { symbol: 'U', name: 'Unity Software Inc.', exchange: 'NYSE' },
  { symbol: 'PATH', name: 'UiPath Inc.', exchange: 'NYSE' },
  { symbol: 'MELI', name: 'MercadoLibre Inc.', exchange: 'NASDAQ' },
  { symbol: 'SE', name: 'Sea Limited', exchange: 'NYSE' },
  { symbol: 'GRAB', name: 'Grab Holdings Limited', exchange: 'NASDAQ' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc.', exchange: 'NASDAQ' },
  { symbol: 'LCID', name: 'Lucid Group Inc.', exchange: 'NASDAQ' },
  { symbol: 'NIO', name: 'NIO Inc.', exchange: 'NYSE' },
  { symbol: 'XPEV', name: 'XPeng Inc.', exchange: 'NYSE' },
  { symbol: 'LI', name: 'Li Auto Inc.', exchange: 'NASDAQ' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc.', exchange: 'NASDAQ' },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc.', exchange: 'NASDAQ' },
  { symbol: 'AFRM', name: 'Affirm Holdings Inc.', exchange: 'NASDAQ' },
  { symbol: 'UPST', name: 'Upstart Holdings Inc.', exchange: 'NASDAQ' },
  { symbol: 'ARM', name: 'Arm Holdings plc', exchange: 'NASDAQ' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.', exchange: 'NASDAQ' },
  { symbol: 'DELL', name: 'Dell Technologies Inc.', exchange: 'NYSE' },
  { symbol: 'HPQ', name: 'HP Inc.', exchange: 'NYSE' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise', exchange: 'NYSE' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', exchange: 'NASDAQ' },
  { symbol: 'PARA', name: 'Paramount Global', exchange: 'NASDAQ' },
  { symbol: 'LUV', name: 'Southwest Airlines Co.', exchange: 'NYSE' },
  { symbol: 'DAL', name: 'Delta Air Lines Inc.', exchange: 'NYSE' },
  { symbol: 'UAL', name: 'United Airlines Holdings', exchange: 'NASDAQ' },
  { symbol: 'AAL', name: 'American Airlines Group', exchange: 'NASDAQ' },
  { symbol: 'CCL', name: 'Carnival Corporation', exchange: 'NYSE' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line', exchange: 'NYSE' },
  { symbol: 'MGM', name: 'MGM Resorts International', exchange: 'NYSE' },
  { symbol: 'WYNN', name: 'Wynn Resorts Limited', exchange: 'NASDAQ' },
  { symbol: 'LVS', name: 'Las Vegas Sands Corp.', exchange: 'NYSE' },
  { symbol: 'DG', name: 'Dollar General Corporation', exchange: 'NYSE' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.', exchange: 'NASDAQ' },
  { symbol: 'ROST', name: 'Ross Stores Inc.', exchange: 'NASDAQ' },
  { symbol: 'TRV', name: 'Travelers Companies Inc.', exchange: 'NYSE' },
  { symbol: 'ALL', name: 'Allstate Corporation', exchange: 'NYSE' },
  { symbol: 'MET', name: 'MetLife Inc.', exchange: 'NYSE' },
  { symbol: 'PRU', name: 'Prudential Financial Inc.', exchange: 'NYSE' },
  { symbol: 'PGR', name: 'Progressive Corporation', exchange: 'NYSE' },
  { symbol: 'CINF', name: 'Cincinnati Financial Corp.', exchange: 'NASDAQ' },
  { symbol: 'WM', name: 'Waste Management Inc.', exchange: 'NYSE' },
  { symbol: 'RSG', name: 'Republic Services Inc.', exchange: 'NYSE' },
  { symbol: 'WEC', name: 'WEC Energy Group Inc.', exchange: 'NYSE' },
  { symbol: 'ES', name: 'Eversource Energy', exchange: 'NYSE' },
  { symbol: 'XEL', name: 'Xcel Energy Inc.', exchange: 'NASDAQ' },
  { symbol: 'ED', name: 'Consolidated Edison Inc.', exchange: 'NYSE' },
  { symbol: 'AWK', name: 'American Water Works Co.', exchange: 'NYSE' },
  { symbol: 'AMT', name: 'American Tower Corporation', exchange: 'NYSE' },
  { symbol: 'EQIX', name: 'Equinix Inc.', exchange: 'NASDAQ' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.', exchange: 'NYSE' },
  { symbol: 'AVB', name: 'AvalonBay Communities Inc.', exchange: 'NYSE' },
  { symbol: 'EQR', name: 'Equity Residential', exchange: 'NYSE' },
  { symbol: 'SBAC', name: 'SBA Communications Corp.', exchange: 'NASDAQ' },
  { symbol: 'WDAY', name: 'Workday Inc.', exchange: 'NASDAQ' },
  { symbol: 'ZM', name: 'Zoom Video Communications', exchange: 'NASDAQ' },
  { symbol: 'OKTA', name: 'Okta Inc.', exchange: 'NASDAQ' },
  { symbol: 'TWLO', name: 'Twilio Inc.', exchange: 'NYSE' },
  { symbol: 'MDB', name: 'MongoDB Inc.', exchange: 'NASDAQ' },
  { symbol: 'TEAM', name: 'Atlassian Corporation', exchange: 'NASDAQ' },
  { symbol: 'HUBS', name: 'HubSpot Inc.', exchange: 'NYSE' },
  { symbol: 'VEEV', name: 'Veeva Systems Inc.', exchange: 'NYSE' },
  { symbol: 'BILL', name: 'BILL Holdings Inc.', exchange: 'NYSE' },
  { symbol: 'DUOL', name: 'Duolingo Inc.', exchange: 'NASDAQ' },
  { symbol: 'APP', name: 'AppLovin Corporation', exchange: 'NASDAQ' },
  { symbol: 'IOT', name: 'Samsara Inc.', exchange: 'NYSE' },

  // === S&P 500 continued ===
  { symbol: 'PPG', name: 'PPG Industries Inc.', exchange: 'NYSE' },
  { symbol: 'WMB', name: 'Williams Companies Inc.', exchange: 'NYSE' },
  { symbol: 'BKR', name: 'Baker Hughes Company', exchange: 'NASDAQ' },
  { symbol: 'DVN', name: 'Devon Energy Corporation', exchange: 'NYSE' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.', exchange: 'NASDAQ' },
  { symbol: 'HES', name: 'Hess Corporation', exchange: 'NYSE' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources', exchange: 'NYSE' },
  { symbol: 'OKE', name: 'ONEOK Inc.', exchange: 'NYSE' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc.', exchange: 'NYSE' },
  { symbol: 'EIX', name: 'Edison International', exchange: 'NYSE' },
  { symbol: 'PEG', name: 'Public Service Enterprise', exchange: 'NYSE' },
  { symbol: 'CEG', name: 'Constellation Energy Corp.', exchange: 'NASDAQ' },
  { symbol: 'PCG', name: 'PG&E Corporation', exchange: 'NYSE' },
  { symbol: 'AES', name: 'AES Corporation', exchange: 'NYSE' },
  { symbol: 'LHX', name: 'L3Harris Technologies', exchange: 'NYSE' },
  { symbol: 'HII', name: 'Huntington Ingalls Industries', exchange: 'NYSE' },
  { symbol: 'TDG', name: 'TransDigm Group Inc.', exchange: 'NYSE' },
  { symbol: 'FICO', name: 'Fair Isaac Corporation', exchange: 'NYSE' },
  { symbol: 'CDW', name: 'CDW Corporation', exchange: 'NASDAQ' },
  { symbol: 'WAB', name: 'Westinghouse Air Brake', exchange: 'NYSE' },
  { symbol: 'PWR', name: 'Quanta Services Inc.', exchange: 'NYSE' },
  { symbol: 'IR', name: 'Ingersoll Rand Inc.', exchange: 'NYSE' },
  { symbol: 'KEYS', name: 'Keysight Technologies', exchange: 'NYSE' },
  { symbol: 'ANSS', name: 'ANSYS Inc.', exchange: 'NASDAQ' },
  { symbol: 'TTWO', name: 'Take-Two Interactive', exchange: 'NASDAQ' },
  { symbol: 'TRGP', name: 'Targa Resources Corp.', exchange: 'NYSE' },
  { symbol: 'COF', name: 'Capital One Financial', exchange: 'NYSE' },
  { symbol: 'DFS', name: 'Discover Financial Services', exchange: 'NYSE' },
  { symbol: 'SYF', name: 'Synchrony Financial', exchange: 'NYSE' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', exchange: 'NASDAQ' },
  { symbol: 'MTB', name: 'M&T Bank Corporation', exchange: 'NYSE' },
  { symbol: 'HBAN', name: 'Huntington Bancshares', exchange: 'NASDAQ' },
  { symbol: 'RF', name: 'Regions Financial Corp.', exchange: 'NYSE' },
  { symbol: 'CFG', name: 'Citizens Financial Group', exchange: 'NYSE' },
  { symbol: 'KEY', name: 'KeyCorp', exchange: 'NYSE' },
  { symbol: 'STT', name: 'State Street Corporation', exchange: 'NYSE' },
  { symbol: 'NTRS', name: 'Northern Trust Corporation', exchange: 'NASDAQ' },
  { symbol: 'C', name: 'Citigroup Inc.', exchange: 'NYSE' },
  { symbol: 'MS', name: 'Morgan Stanley', exchange: 'NYSE' },
  { symbol: 'SIVB', name: 'SVB Financial Group', exchange: 'NASDAQ' },
  { symbol: 'EFX', name: 'Equifax Inc.', exchange: 'NYSE' },
  { symbol: 'BR', name: 'Broadridge Financial', exchange: 'NYSE' },
  { symbol: 'TROW', name: 'T. Rowe Price Group', exchange: 'NASDAQ' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances', exchange: 'NYSE' },
  { symbol: 'ALB', name: 'Albemarle Corporation', exchange: 'NYSE' },
  { symbol: 'LYB', name: 'LyondellBasell Industries', exchange: 'NYSE' },
  { symbol: 'VMC', name: 'Vulcan Materials Company', exchange: 'NYSE' },
  { symbol: 'MLM', name: 'Martin Marietta Materials', exchange: 'NYSE' },
  { symbol: 'NUE', name: 'Nucor Corporation', exchange: 'NYSE' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc.', exchange: 'NASDAQ' },
  { symbol: 'PKG', name: 'Packaging Corp. of America', exchange: 'NYSE' },
  { symbol: 'IP', name: 'International Paper Co.', exchange: 'NYSE' },
  { symbol: 'AVY', name: 'Avery Dennison Corporation', exchange: 'NYSE' },
  { symbol: 'SWK', name: 'Stanley Black & Decker', exchange: 'NYSE' },
  { symbol: 'PH', name: 'Parker-Hannifin Corp.', exchange: 'NYSE' },
  { symbol: 'EMN', name: 'Eastman Chemical Company', exchange: 'NYSE' },
  { symbol: 'CE', name: 'Celanese Corporation', exchange: 'NYSE' },
  { symbol: 'FMC', name: 'FMC Corporation', exchange: 'NYSE' },
  { symbol: 'MOH', name: 'Molina Healthcare Inc.', exchange: 'NYSE' },
  { symbol: 'CNC', name: 'Centene Corporation', exchange: 'NYSE' },
  { symbol: 'ELV', name: 'Elevance Health Inc.', exchange: 'NYSE' },
  { symbol: 'CVS', name: 'CVS Health Corporation', exchange: 'NYSE' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance', exchange: 'NASDAQ' },
  { symbol: 'CAH', name: 'Cardinal Health Inc.', exchange: 'NYSE' },
  { symbol: 'BAX', name: 'Baxter International Inc.', exchange: 'NYSE' },
  { symbol: 'BDX', name: 'Becton Dickinson and Co.', exchange: 'NYSE' },
  { symbol: 'ZBH', name: 'Zimmer Biomet Holdings', exchange: 'NYSE' },
  { symbol: 'HOLX', name: 'Hologic Inc.', exchange: 'NASDAQ' },
  { symbol: 'ALGN', name: 'Align Technology Inc.', exchange: 'NASDAQ' },
  { symbol: 'ILMN', name: 'Illumina Inc.', exchange: 'NASDAQ' },
  { symbol: 'MRNA', name: 'Moderna Inc.', exchange: 'NASDAQ' },
  { symbol: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE' },
  { symbol: 'LIN', name: 'Linde plc', exchange: 'NASDAQ' },
  { symbol: 'APH', name: 'Amphenol Corporation', exchange: 'NYSE' },
  { symbol: 'GLW', name: 'Corning Incorporated', exchange: 'NYSE' },
  { symbol: 'TEL', name: 'TE Connectivity Ltd.', exchange: 'NYSE' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corp.', exchange: 'NASDAQ' },
  { symbol: 'TYL', name: 'Tyler Technologies Inc.', exchange: 'NYSE' },
  { symbol: 'EPAM', name: 'EPAM Systems Inc.', exchange: 'NYSE' },
  { symbol: 'SWKS', name: 'Skyworks Solutions Inc.', exchange: 'NASDAQ' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems', exchange: 'NASDAQ' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.', exchange: 'NASDAQ' },
  { symbol: 'SEDG', name: 'SolarEdge Technologies', exchange: 'NASDAQ' },
  { symbol: 'FSLR', name: 'First Solar Inc.', exchange: 'NASDAQ' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc.', exchange: 'NYSE' },
  { symbol: 'WST', name: 'West Pharmaceutical Services', exchange: 'NYSE' },
  { symbol: 'PODD', name: 'Insulet Corporation', exchange: 'NASDAQ' },
  { symbol: 'STE', name: 'STERIS plc', exchange: 'NYSE' },
  { symbol: 'MTD', name: 'Mettler-Toledo International', exchange: 'NYSE' },
  { symbol: 'WAT', name: 'Waters Corporation', exchange: 'NYSE' },
  { symbol: 'TER', name: 'Teradyne Inc.', exchange: 'NASDAQ' },
  { symbol: 'NTAP', name: 'NetApp Inc.', exchange: 'NASDAQ' },
  { symbol: 'WDC', name: 'Western Digital Corp.', exchange: 'NASDAQ' },
  { symbol: 'STX', name: 'Seagate Technology', exchange: 'NASDAQ' },

  // === Popular ETFs ===
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', exchange: 'NYSE Arca' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF', exchange: 'NYSE Arca' },
  { symbol: 'IVV', name: 'iShares Core S&P 500 ETF', exchange: 'NYSE Arca' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', exchange: 'NASDAQ' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF', exchange: 'NYSE Arca' },
  { symbol: 'VEA', name: 'Vanguard FTSE Developed Markets ETF', exchange: 'NYSE Arca' },
  { symbol: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF', exchange: 'NYSE Arca' },
  { symbol: 'IEFA', name: 'iShares Core MSCI EAFE ETF', exchange: 'NYSE Arca' },
  { symbol: 'IEMG', name: 'iShares Core MSCI Emerging Markets ETF', exchange: 'NYSE Arca' },
  { symbol: 'AGG', name: 'iShares Core U.S. Aggregate Bond ETF', exchange: 'NYSE Arca' },
  { symbol: 'BND', name: 'Vanguard Total Bond Market ETF', exchange: 'NASDAQ' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', exchange: 'NASDAQ' },
  { symbol: 'LQD', name: 'iShares iBoxx $ Investment Grade Corporate Bond ETF', exchange: 'NYSE Arca' },
  { symbol: 'HYG', name: 'iShares iBoxx $ High Yield Corporate Bond ETF', exchange: 'NYSE Arca' },
  { symbol: 'GLD', name: 'SPDR Gold Shares', exchange: 'NYSE Arca' },
  { symbol: 'IAU', name: 'iShares Gold Trust', exchange: 'NYSE Arca' },
  { symbol: 'SLV', name: 'iShares Silver Trust', exchange: 'NYSE Arca' },
  { symbol: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF', exchange: 'NYSE Arca' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', exchange: 'NYSE Arca' },
  { symbol: 'IWF', name: 'iShares Russell 1000 Growth ETF', exchange: 'NYSE Arca' },
  { symbol: 'IWD', name: 'iShares Russell 1000 Value ETF', exchange: 'NYSE Arca' },
  { symbol: 'EEM', name: 'iShares MSCI Emerging Markets ETF', exchange: 'NYSE Arca' },
  { symbol: 'EFA', name: 'iShares MSCI EAFE ETF', exchange: 'NYSE Arca' },
  { symbol: 'VIG', name: 'Vanguard Dividend Appreciation ETF', exchange: 'NYSE Arca' },
  { symbol: 'VYM', name: 'Vanguard High Dividend Yield ETF', exchange: 'NYSE Arca' },
  { symbol: 'SCHD', name: 'Schwab U.S. Dividend Equity ETF', exchange: 'NYSE Arca' },
  { symbol: 'VGT', name: 'Vanguard Information Technology ETF', exchange: 'NYSE Arca' },
  { symbol: 'XLK', name: 'Technology Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLF', name: 'Financial Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLV', name: 'Health Care Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLE', name: 'Energy Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLI', name: 'Industrial Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLY', name: 'Consumer Discretionary Select Sector SPDR', exchange: 'NYSE Arca' },
  { symbol: 'XLP', name: 'Consumer Staples Select Sector SPDR', exchange: 'NYSE Arca' },
  { symbol: 'XLU', name: 'Utilities Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLB', name: 'Materials Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLRE', name: 'Real Estate Select Sector SPDR Fund', exchange: 'NYSE Arca' },
  { symbol: 'XLC', name: 'Communication Services Select Sector SPDR', exchange: 'NYSE Arca' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF', exchange: 'NYSE Arca' },
  { symbol: 'ARKW', name: 'ARK Next Generation Internet ETF', exchange: 'NYSE Arca' },
  { symbol: 'ARKG', name: 'ARK Genomic Revolution ETF', exchange: 'NYSE Arca' },
  { symbol: 'ARKF', name: 'ARK Fintech Innovation ETF', exchange: 'NYSE Arca' },
  { symbol: 'SOXL', name: 'Direxion Daily Semiconductor Bull 3X', exchange: 'NYSE Arca' },
  { symbol: 'SOXS', name: 'Direxion Daily Semiconductor Bear 3X', exchange: 'NYSE Arca' },
  { symbol: 'TQQQ', name: 'ProShares UltraPro QQQ', exchange: 'NASDAQ' },
  { symbol: 'SQQQ', name: 'ProShares UltraPro Short QQQ', exchange: 'NASDAQ' },
  { symbol: 'SPXL', name: 'Direxion Daily S&P 500 Bull 3X', exchange: 'NYSE Arca' },
  { symbol: 'SPXS', name: 'Direxion Daily S&P 500 Bear 3X', exchange: 'NYSE Arca' },
  { symbol: 'VNQ', name: 'Vanguard Real Estate ETF', exchange: 'NYSE Arca' },
  { symbol: 'KWEB', name: 'KraneShares CSI China Internet ETF', exchange: 'NYSE Arca' },
  { symbol: 'FXI', name: 'iShares China Large-Cap ETF', exchange: 'NYSE Arca' },
  { symbol: 'MCHI', name: 'iShares MSCI China ETF', exchange: 'NASDAQ' },
  { symbol: 'EWJ', name: 'iShares MSCI Japan ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWZ', name: 'iShares MSCI Brazil ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWT', name: 'iShares MSCI Taiwan ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWY', name: 'iShares MSCI South Korea ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWS', name: 'iShares MSCI Singapore ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWH', name: 'iShares MSCI Hong Kong ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWA', name: 'iShares MSCI Australia ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWG', name: 'iShares MSCI Germany ETF', exchange: 'NYSE Arca' },
  { symbol: 'EWU', name: 'iShares MSCI United Kingdom ETF', exchange: 'NYSE Arca' },
  { symbol: 'INDA', name: 'iShares MSCI India ETF', exchange: 'NYSE Arca' },
  { symbol: 'SMH', name: 'VanEck Semiconductor ETF', exchange: 'NASDAQ' },
  { symbol: 'SOXX', name: 'iShares Semiconductor ETF', exchange: 'NASDAQ' },
  { symbol: 'XBI', name: 'SPDR S&P Biotech ETF', exchange: 'NYSE Arca' },
  { symbol: 'IBB', name: 'iShares Biotechnology ETF', exchange: 'NASDAQ' },
  { symbol: 'HACK', name: 'ETFMG Prime Cyber Security ETF', exchange: 'NYSE Arca' },
  { symbol: 'BOTZ', name: 'Global X Robotics & AI ETF', exchange: 'NASDAQ' },
  { symbol: 'ICLN', name: 'iShares Global Clean Energy ETF', exchange: 'NASDAQ' },
  { symbol: 'TAN', name: 'Invesco Solar ETF', exchange: 'NYSE Arca' },
  { symbol: 'JEPI', name: 'JPMorgan Equity Premium Income ETF', exchange: 'NYSE Arca' },
  { symbol: 'JEPQ', name: 'JPMorgan Nasdaq Equity Premium Income ETF', exchange: 'NASDAQ' },

  // === Major Indices ===
  { symbol: '^GSPC', name: 'S&P 500', exchange: 'SNP' },
  { symbol: '^DJI', name: 'Dow Jones Industrial Average', exchange: 'DJI' },
  { symbol: '^IXIC', name: 'NASDAQ Composite', exchange: 'NASDAQ' },
  { symbol: '^RUT', name: 'Russell 2000', exchange: 'NYSE' },
  { symbol: '^VIX', name: 'CBOE Volatility Index', exchange: 'CBOE' },
  { symbol: '^TNX', name: 'Treasury Yield 10 Years', exchange: 'CBOE' },
  { symbol: '^FTSE', name: 'FTSE 100', exchange: 'London' },
  { symbol: '^N225', name: 'Nikkei 225', exchange: 'Osaka' },
  { symbol: '^HSI', name: 'Hang Seng Index', exchange: 'HKSE' },
  { symbol: '^STI', name: 'Straits Times Index', exchange: 'SGX' },
  { symbol: '^KLSE', name: 'FTSE Bursa Malaysia KLCI', exchange: 'Kuala Lumpur' },

  // === Singapore (SGX) ===
  { symbol: 'D05.SI', name: 'DBS Group Holdings Ltd', exchange: 'SGX' },
  { symbol: 'O39.SI', name: 'Oversea-Chinese Banking Corp', exchange: 'SGX' },
  { symbol: 'U11.SI', name: 'United Overseas Bank Ltd', exchange: 'SGX' },
  { symbol: 'Z74.SI', name: 'Singapore Telecommunications', exchange: 'SGX' },
  { symbol: 'F34.SI', name: 'Wilmar International Ltd', exchange: 'SGX' },
  { symbol: 'BN4.SI', name: 'Keppel Ltd', exchange: 'SGX' },
  { symbol: 'C6L.SI', name: 'Singapore Airlines Ltd', exchange: 'SGX' },
  { symbol: 'G13.SI', name: 'Genting Singapore Limited', exchange: 'SGX' },
  { symbol: 'Y92.SI', name: 'Thai Beverage PCL', exchange: 'SGX' },
  { symbol: 'A17U.SI', name: 'CapitaLand Ascendas REIT', exchange: 'SGX' },
  { symbol: 'C38U.SI', name: 'CapitaLand Integrated Commercial Trust', exchange: 'SGX' },
  { symbol: 'ME8U.SI', name: 'Mapletree Industrial Trust', exchange: 'SGX' },
  { symbol: 'N2IU.SI', name: 'Mapletree Pan Asia Commercial Trust', exchange: 'SGX' },
  { symbol: 'M44U.SI', name: 'Mapletree Logistics Trust', exchange: 'SGX' },
  { symbol: 'AJBU.SI', name: 'Keppel DC REIT', exchange: 'SGX' },
  { symbol: 'J36.SI', name: 'Jardine Matheson Holdings', exchange: 'SGX' },
  { symbol: 'J37.SI', name: 'Jardine Strategic Holdings', exchange: 'SGX' },
  { symbol: 'C09.SI', name: 'City Developments Limited', exchange: 'SGX' },
  { symbol: 'U14.SI', name: 'UOL Group Limited', exchange: 'SGX' },
  { symbol: 'H78.SI', name: 'Hongkong Land Holdings', exchange: 'SGX' },
  { symbol: 'S58.SI', name: 'SATS Ltd', exchange: 'SGX' },
  { symbol: 'S63.SI', name: 'Singapore Technologies Engineering', exchange: 'SGX' },
  { symbol: 'S68.SI', name: 'Singapore Exchange Limited', exchange: 'SGX' },
  { symbol: 'V03.SI', name: 'Venture Corporation Limited', exchange: 'SGX' },
  { symbol: 'BS6.SI', name: 'Yangzijiang Shipbuilding', exchange: 'SGX' },
  { symbol: 'CC3.SI', name: 'StarHub Ltd', exchange: 'SGX' },
  { symbol: 'U96.SI', name: 'Sembcorp Industries Ltd', exchange: 'SGX' },
  { symbol: 'EMI.SI', name: 'Emperador Inc', exchange: 'SGX' },
  { symbol: 'BUOU.SI', name: 'Frasers Logistics & Commercial Trust', exchange: 'SGX' },
  { symbol: 'TQ5.SI', name: 'Frasers Centrepoint Trust', exchange: 'SGX' },
  { symbol: 'J69U.SI', name: 'Frasers Hospitality Trust', exchange: 'SGX' },
  { symbol: 'ES3.SI', name: 'SPDR STI ETF', exchange: 'SGX' },
  { symbol: 'CLR.SI', name: 'Nikko AM STI ETF', exchange: 'SGX' },
  { symbol: 'K71U.SI', name: 'Keppel REIT', exchange: 'SGX' },
  { symbol: 'T39.SI', name: 'Singapore Press Holdings', exchange: 'SGX' },
  { symbol: 'H02.SI', name: 'Haw Par Corporation Ltd', exchange: 'SGX' },
  { symbol: 'AWX.SI', name: 'AEM Holdings Ltd', exchange: 'SGX' },
  { symbol: 'RE4.SI', name: 'Sheng Siong Group Ltd', exchange: 'SGX' },

  // === Hong Kong (HKEX) ===
  { symbol: '0700.HK', name: 'Tencent Holdings Limited', exchange: 'HKSE' },
  { symbol: '9988.HK', name: 'Alibaba Group Holding', exchange: 'HKSE' },
  { symbol: '9618.HK', name: 'JD.com Inc.', exchange: 'HKSE' },
  { symbol: '3690.HK', name: 'Meituan', exchange: 'HKSE' },
  { symbol: '1211.HK', name: 'BYD Company Limited', exchange: 'HKSE' },
  { symbol: '0005.HK', name: 'HSBC Holdings plc', exchange: 'HKSE' },
  { symbol: '0941.HK', name: 'China Mobile Limited', exchange: 'HKSE' },
  { symbol: '0939.HK', name: 'China Construction Bank', exchange: 'HKSE' },
  { symbol: '1398.HK', name: 'Industrial & Commercial Bank of China', exchange: 'HKSE' },
  { symbol: '2318.HK', name: 'Ping An Insurance Group', exchange: 'HKSE' },
  { symbol: '0388.HK', name: 'Hong Kong Exchanges & Clearing', exchange: 'HKSE' },
  { symbol: '0001.HK', name: 'CK Hutchison Holdings', exchange: 'HKSE' },
  { symbol: '0016.HK', name: 'Sun Hung Kai Properties', exchange: 'HKSE' },
  { symbol: '2382.HK', name: 'Sunny Optical Technology', exchange: 'HKSE' },
  { symbol: '9999.HK', name: 'NetEase Inc.', exchange: 'HKSE' },
  { symbol: '0020.HK', name: 'SenseTime Group Inc.', exchange: 'HKSE' },
  { symbol: '9888.HK', name: 'Baidu Inc.', exchange: 'HKSE' },
  { symbol: '1024.HK', name: 'Kuaishou Technology', exchange: 'HKSE' },
  { symbol: '2020.HK', name: 'ANTA Sports Products', exchange: 'HKSE' },
  { symbol: '0027.HK', name: 'Galaxy Entertainment Group', exchange: 'HKSE' },
  { symbol: '1928.HK', name: 'Sands China Ltd', exchange: 'HKSE' },
  { symbol: '2269.HK', name: 'WuXi Biologics', exchange: 'HKSE' },

  // === China A-Shares (via US ADRs) ===
  { symbol: 'BABA', name: 'Alibaba Group Holding', exchange: 'NYSE' },
  { symbol: 'JD', name: 'JD.com Inc.', exchange: 'NASDAQ' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.', exchange: 'NASDAQ' },
  { symbol: 'BIDU', name: 'Baidu Inc.', exchange: 'NASDAQ' },
  { symbol: 'NTES', name: 'NetEase Inc.', exchange: 'NASDAQ' },
  { symbol: 'BILI', name: 'Bilibili Inc.', exchange: 'NASDAQ' },
  { symbol: 'TME', name: 'Tencent Music Entertainment', exchange: 'NYSE' },
  { symbol: 'TCOM', name: 'Trip.com Group Limited', exchange: 'NASDAQ' },
  { symbol: 'FUTU', name: 'Futu Holdings Limited', exchange: 'NASDAQ' },
  { symbol: 'ZTO', name: 'ZTO Express Inc.', exchange: 'NYSE' },

  // === Japan ===
  { symbol: '7203.T', name: 'Toyota Motor Corporation', exchange: 'Tokyo' },
  { symbol: '6758.T', name: 'Sony Group Corporation', exchange: 'Tokyo' },
  { symbol: '6861.T', name: 'Keyence Corporation', exchange: 'Tokyo' },
  { symbol: '8306.T', name: 'Mitsubishi UFJ Financial', exchange: 'Tokyo' },
  { symbol: '9984.T', name: 'SoftBank Group Corp.', exchange: 'Tokyo' },
  { symbol: '6902.T', name: 'Denso Corporation', exchange: 'Tokyo' },
  { symbol: '9432.T', name: 'Nippon Telegraph & Telephone', exchange: 'Tokyo' },
  { symbol: '4063.T', name: 'Shin-Etsu Chemical Co.', exchange: 'Tokyo' },
  { symbol: '6501.T', name: 'Hitachi Ltd.', exchange: 'Tokyo' },
  { symbol: '7267.T', name: 'Honda Motor Co. Ltd.', exchange: 'Tokyo' },
  { symbol: '8035.T', name: 'Tokyo Electron Limited', exchange: 'Tokyo' },
  { symbol: '7741.T', name: 'HOYA Corporation', exchange: 'Tokyo' },
  { symbol: '6098.T', name: 'Recruit Holdings Co.', exchange: 'Tokyo' },
  { symbol: '4519.T', name: 'Chugai Pharmaceutical', exchange: 'Tokyo' },
  { symbol: '6954.T', name: 'FANUC Corporation', exchange: 'Tokyo' },
  { symbol: '7974.T', name: 'Nintendo Co. Ltd.', exchange: 'Tokyo' },

  // === Europe ===
  { symbol: 'ASML', name: 'ASML Holding N.V.', exchange: 'NASDAQ' },
  { symbol: 'SAP', name: 'SAP SE', exchange: 'NYSE' },
  { symbol: 'NVO', name: 'Novo Nordisk A/S', exchange: 'NYSE' },
  { symbol: 'TM', name: 'Toyota Motor Corporation', exchange: 'NYSE' },
  { symbol: 'SONY', name: 'Sony Group Corporation', exchange: 'NYSE' },
  { symbol: 'SNY', name: 'Sanofi', exchange: 'NASDAQ' },
  { symbol: 'AZN', name: 'AstraZeneca PLC', exchange: 'NASDAQ' },
  { symbol: 'NVS', name: 'Novartis AG', exchange: 'NYSE' },
  { symbol: 'GSK', name: 'GSK plc', exchange: 'NYSE' },
  { symbol: 'UL', name: 'Unilever PLC', exchange: 'NYSE' },
  { symbol: 'SHEL', name: 'Shell plc', exchange: 'NYSE' },
  { symbol: 'BP', name: 'BP p.l.c.', exchange: 'NYSE' },
  { symbol: 'TTE', name: 'TotalEnergies SE', exchange: 'NYSE' },
  { symbol: 'EQNR', name: 'Equinor ASA', exchange: 'NYSE' },
  { symbol: 'RIO', name: 'Rio Tinto Group', exchange: 'NYSE' },
  { symbol: 'BHP', name: 'BHP Group Limited', exchange: 'NYSE' },
  { symbol: 'VALE', name: 'Vale S.A.', exchange: 'NYSE' },
  { symbol: 'DEO', name: 'Diageo plc', exchange: 'NYSE' },
  { symbol: 'BTI', name: 'British American Tobacco', exchange: 'NYSE' },
  { symbol: 'HSBC', name: 'HSBC Holdings plc', exchange: 'NYSE' },
  { symbol: 'UBS', name: 'UBS Group AG', exchange: 'NYSE' },
  { symbol: 'CS', name: 'Credit Suisse Group AG', exchange: 'NYSE' },
  { symbol: 'DB', name: 'Deutsche Bank AG', exchange: 'NYSE' },
  { symbol: 'ING', name: 'ING Groep N.V.', exchange: 'NYSE' },
  { symbol: 'SPOT', name: 'Spotify Technology S.A.', exchange: 'NYSE' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.', exchange: 'NASDAQ' },

  // === Malaysia (KLSE) ===
  { symbol: '1155.KL', name: 'Malayan Banking Bhd (Maybank)', exchange: 'Kuala Lumpur' },
  { symbol: '1295.KL', name: 'Public Bank Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '6888.KL', name: 'CIMB Group Holdings Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '1082.KL', name: 'Hong Leong Financial Group', exchange: 'Kuala Lumpur' },
  { symbol: '4715.KL', name: 'Genting Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '3182.KL', name: 'Genting Malaysia Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '5347.KL', name: 'Tenaga Nasional Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '4863.KL', name: 'Telekom Malaysia Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '6012.KL', name: 'Maxis Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '6947.KL', name: 'DiGi.Com Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '5183.KL', name: 'Petronas Chemicals Group', exchange: 'Kuala Lumpur' },
  { symbol: '5225.KL', name: 'IHH Healthcare Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '5285.KL', name: 'Sime Darby Plantation Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '1023.KL', name: 'CIMB Group Holdings', exchange: 'Kuala Lumpur' },
  { symbol: '4197.KL', name: 'Sime Darby Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '2445.KL', name: 'Kuala Lumpur Kepong Bhd', exchange: 'Kuala Lumpur' },
  { symbol: '6742.KL', name: 'YTL Power International Bhd', exchange: 'Kuala Lumpur' },

  // === India (via US ADRs) ===
  { symbol: 'INFY', name: 'Infosys Limited', exchange: 'NYSE' },
  { symbol: 'WIT', name: 'Wipro Limited', exchange: 'NYSE' },
  { symbol: 'HDB', name: 'HDFC Bank Limited', exchange: 'NYSE' },
  { symbol: 'IBN', name: 'ICICI Bank Limited', exchange: 'NYSE' },
  { symbol: 'SIFY', name: 'Sify Technologies Limited', exchange: 'NASDAQ' },
  { symbol: 'TTM', name: 'Tata Motors Limited', exchange: 'NYSE' },
  { symbol: 'RDY', name: 'Dr. Reddy\'s Laboratories', exchange: 'NYSE' },

  // === Australia ===
  { symbol: 'CBA.AX', name: 'Commonwealth Bank of Australia', exchange: 'ASX' },
  { symbol: 'BHP.AX', name: 'BHP Group Limited', exchange: 'ASX' },
  { symbol: 'CSL.AX', name: 'CSL Limited', exchange: 'ASX' },
  { symbol: 'NAB.AX', name: 'National Australia Bank', exchange: 'ASX' },
  { symbol: 'WBC.AX', name: 'Westpac Banking Corp.', exchange: 'ASX' },
  { symbol: 'ANZ.AX', name: 'ANZ Group Holdings', exchange: 'ASX' },
  { symbol: 'WES.AX', name: 'Wesfarmers Limited', exchange: 'ASX' },
  { symbol: 'WOW.AX', name: 'Woolworths Group Limited', exchange: 'ASX' },
  { symbol: 'FMG.AX', name: 'Fortescue Ltd', exchange: 'ASX' },
  { symbol: 'RIO.AX', name: 'Rio Tinto Limited', exchange: 'ASX' },

  // === Crypto-related ===
  { symbol: 'BTC-USD', name: 'Bitcoin USD', exchange: 'CCC' },
  { symbol: 'ETH-USD', name: 'Ethereum USD', exchange: 'CCC' },
  { symbol: 'MSTR', name: 'MicroStrategy Incorporated', exchange: 'NASDAQ' },
  { symbol: 'MARA', name: 'Marathon Digital Holdings', exchange: 'NASDAQ' },
  { symbol: 'RIOT', name: 'Riot Platforms Inc.', exchange: 'NASDAQ' },
  { symbol: 'IBIT', name: 'iShares Bitcoin Trust ETF', exchange: 'NASDAQ' },
  { symbol: 'GBTC', name: 'Grayscale Bitcoin Trust', exchange: 'NYSE Arca' },

  // === Additional popular / meme stocks ===
  { symbol: 'GME', name: 'GameStop Corp.', exchange: 'NYSE' },
  { symbol: 'AMC', name: 'AMC Entertainment Holdings', exchange: 'NYSE' },
  { symbol: 'BBBY', name: 'Bed Bath & Beyond Inc.', exchange: 'NASDAQ' },
  { symbol: 'BB', name: 'BlackBerry Limited', exchange: 'NYSE' },
  { symbol: 'TLRY', name: 'Tilray Brands Inc.', exchange: 'NASDAQ' },
  { symbol: 'SPCE', name: 'Virgin Galactic Holdings', exchange: 'NYSE' },
  { symbol: 'CLOV', name: 'Clover Health Investments', exchange: 'NASDAQ' },
  { symbol: 'WISH', name: 'ContextLogic Inc.', exchange: 'NASDAQ' },
  { symbol: 'BYND', name: 'Beyond Meat Inc.', exchange: 'NASDAQ' },
  { symbol: 'CHPT', name: 'ChargePoint Holdings Inc.', exchange: 'NYSE' },
  { symbol: 'PLUG', name: 'Plug Power Inc.', exchange: 'NASDAQ' },
  { symbol: 'OPEN', name: 'Opendoor Technologies Inc.', exchange: 'NASDAQ' },

  // === UK (London) ===
  { symbol: 'SHEL.L', name: 'Shell plc', exchange: 'London' },
  { symbol: 'AZN.L', name: 'AstraZeneca PLC', exchange: 'London' },
  { symbol: 'HSBA.L', name: 'HSBC Holdings plc', exchange: 'London' },
  { symbol: 'ULVR.L', name: 'Unilever PLC', exchange: 'London' },
  { symbol: 'BP.L', name: 'BP p.l.c.', exchange: 'London' },
  { symbol: 'GSK.L', name: 'GSK plc', exchange: 'London' },
  { symbol: 'RIO.L', name: 'Rio Tinto plc', exchange: 'London' },
  { symbol: 'DGE.L', name: 'Diageo plc', exchange: 'London' },
  { symbol: 'BATS.L', name: 'British American Tobacco', exchange: 'London' },
  { symbol: 'LSEG.L', name: 'London Stock Exchange Group', exchange: 'London' },

  // === Additional large US stocks ===
  { symbol: 'CHTR', name: 'Charter Communications Inc.', exchange: 'NASDAQ' },
  { symbol: 'AMP', name: 'Ameriprise Financial Inc.', exchange: 'NYSE' },
  { symbol: 'HIG', name: 'Hartford Financial Services', exchange: 'NYSE' },
  { symbol: 'EQT', name: 'EQT Corporation', exchange: 'NYSE' },
  { symbol: 'RMD', name: 'ResMed Inc.', exchange: 'NYSE' },
  { symbol: 'LPLA', name: 'LPL Financial Holdings', exchange: 'NASDAQ' },
  { symbol: 'ARES', name: 'Ares Management Corporation', exchange: 'NYSE' },
  { symbol: 'KKR', name: 'KKR & Co. Inc.', exchange: 'NYSE' },
  { symbol: 'APO', name: 'Apollo Global Management', exchange: 'NYSE' },
  { symbol: 'CG', name: 'Carlyle Group Inc.', exchange: 'NASDAQ' },
  { symbol: 'OWL', name: 'Blue Owl Capital Inc.', exchange: 'NYSE' },
  { symbol: 'TPL', name: 'Texas Pacific Land Corp.', exchange: 'NYSE' },
  { symbol: 'VST', name: 'Vistra Corp.', exchange: 'NYSE' },
  { symbol: 'NRG', name: 'NRG Energy Inc.', exchange: 'NYSE' },
  { symbol: 'AXON', name: 'Axon Enterprise Inc.', exchange: 'NASDAQ' },
  { symbol: 'DECK', name: 'Deckers Outdoor Corporation', exchange: 'NYSE' },
  { symbol: 'ON', name: 'ON Semiconductor Corp.', exchange: 'NASDAQ' },
  { symbol: 'TSCO', name: 'Tractor Supply Company', exchange: 'NASDAQ' },
  { symbol: 'ULTA', name: 'Ulta Beauty Inc.', exchange: 'NASDAQ' },
  { symbol: 'LW', name: 'Lamb Weston Holdings Inc.', exchange: 'NYSE' },
  { symbol: 'WING', name: 'Wingstop Inc.', exchange: 'NASDAQ' },
  { symbol: 'TXRH', name: 'Texas Roadhouse Inc.', exchange: 'NASDAQ' },
  { symbol: 'CAVA', name: 'CAVA Group Inc.', exchange: 'NYSE' },
  { symbol: 'TOST', name: 'Toast Inc.', exchange: 'NYSE' },
  { symbol: 'DT', name: 'Dynatrace Inc.', exchange: 'NYSE' },
  { symbol: 'CFLT', name: 'Confluent Inc.', exchange: 'NASDAQ' },
  { symbol: 'GTLB', name: 'GitLab Inc.', exchange: 'NASDAQ' },
  { symbol: 'S', name: 'SentinelOne Inc.', exchange: 'NYSE' },
  { symbol: 'CYBR', name: 'CyberArk Software Ltd.', exchange: 'NASDAQ' },
  { symbol: 'RPD', name: 'Rapid7 Inc.', exchange: 'NASDAQ' },
  { symbol: 'PCTY', name: 'Paylocity Holding Corp.', exchange: 'NASDAQ' },
  { symbol: 'PAYC', name: 'Paycom Software Inc.', exchange: 'NYSE' },
  { symbol: 'CELH', name: 'Celsius Holdings Inc.', exchange: 'NASDAQ' },
];
